# Builds a JAR file and uses that to build and push a Docker Image to Docker Hub

name: Publish Docker Image

on:
  release:
    types: [published]

jobs:
  build: 
    
    name: Build JAR 
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Store the JAR file
        uses: actions/upload-artifact@v2
        with:
          name: jar
          path: ./target/${{ secrets.JAR_NAME }}
    
  push_to_registry:
    
    name: Push Docker Image
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Create Target directory
        run: mkdir -p target
      - name: Get Jar from Build
        uses: actions/download-artifact@v2
        with:
          name: jar
          path: ./target
      - name: Display directory structure
        run: ls -R
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_NAMESPACE }}/${{ secrets.DOCKER_REPOSITORY }}
          tags: api
